const { renderKpiStrip } = require('./kpi-strip');
const { renderProofGallery } = require('./proof-gallery');
const { renderRiskRegister } = require('./risk-register');
const { renderValueChain } = require('./value-chain');
const { renderBarChart } = require('./bar-chart');
const { renderChartSpec } = require('./chart-renderer');
const { renderFunnelChart } = require('./funnel-chart');
const { renderHeatmapChart } = require('./heatmap-chart');
const { renderLineChart } = require('./line-chart');
const { renderMatrixChart } = require('./matrix-chart');
const { renderParetoChart } = require('./pareto-chart');
const { renderScorecard } = require('./scorecard');
const { renderTableWithCommentary } = require('./table-with-commentary');
const { renderWaterfallChart } = require('./waterfall-chart');
const {
  renderBeautyChannelStructure,
  renderBeautyEfficacyTable,
  renderBeautyMemberRepurchase,
  renderBeautyPriceBandMatrix,
  renderBeautyProofGallery,
  renderBeautyReviewSentiment,
  renderBeautySkuMatrix,
  renderBeautySocialFunnel,
  renderBeautySustainabilityMatrix
} = require('./beauty-charts');

const CAPABILITY_IDS = [
  ['accent-rail', ['native'], 'native-decoration'],
  ['acceptance-gate', ['native'], 'native-decoration'],
  ['activation-funnel', ['native'], 'native-decoration'],
  ['adoption-funnel', ['native'], 'native-decoration'],
  ['alert-checkpoint', ['native'], 'native-decoration'],
  ['alert-severity-tag', ['native'], 'native-decoration'],
  ['api-connector-node', ['native'], 'native-decoration'],
  ['asset-readout-strip', ['native'], 'native-decoration'],
  ['asset-status-chip', ['native'], 'native-decoration'],
  ['authorization-stamp', ['native'], 'native-decoration'],
  ['back-cover-anchor', ['native'], 'native-decoration'],
  ['bar-chart', ['native', 'overlay'], 'chart'],
  ['beauty-channel-structure', ['native', 'overlay'], 'chart'],
  ['beauty-efficacy-table', ['native', 'overlay'], 'chart'],
  ['beauty-member-repurchase', ['native', 'overlay'], 'chart'],
  ['beauty-price-band-matrix', ['native', 'overlay'], 'chart'],
  ['beauty-proof-gallery', ['native', 'overlay'], 'chart'],
  ['beauty-review-sentiment', ['native', 'overlay'], 'chart'],
  ['beauty-sku-matrix', ['native', 'overlay'], 'chart'],
  ['beauty-social-funnel', ['native', 'overlay'], 'chart'],
  ['beauty-sustainability-matrix', ['native', 'overlay'], 'chart'],
  ['brand-proof-card', ['native'], 'native-decoration'],
  ['brand-proof-caption', ['native', 'overlay'], 'caption'],
  ['brand-world-caption', ['native'], 'caption'],
  ['brand-world-hero', ['native'], 'visual'],
  ['business-proof-rail', ['native'], 'flow'],
  ['campaign-strip', ['native'], 'native-decoration'],
  ['campaign-to-member-rail', ['native'], 'flow'],
  ['capability-layer-stack', ['native'], 'flow'],
  ['capacity-fact-tags', ['native'], 'native-decoration'],
  ['capital-bridge', ['native'], 'native-decoration'],
  ['caption-bar', ['native', 'overlay'], 'caption'],
  ['care-loop-anchor', ['native'], 'native-decoration'],
  ['channel-risk-tag', ['native'], 'native-decoration'],
  ['chapter-index-rail', ['native'], 'native-decoration'],
  ['chart-commentary-panel', ['native', 'overlay'], 'commentary'],
  ['commentary-panel', ['native', 'overlay'], 'commentary'],
  ['contact-block', ['native'], 'closing'],
  ['content-to-member-rail', ['native'], 'flow'],
  ['content-card-grid', ['native'], 'content'],
  ['control-tag', ['native'], 'governance'],
  ['decision-caption', ['native'], 'closing'],
  ['decision-gate', ['native'], 'closing'],
  ['decision-panel', ['native'], 'closing'],
  ['decorative-orb', ['native'], 'native-decoration'],
  ['disclosure-footnote', ['native'], 'source'],
  ['dispatch-rail', ['native'], 'flow'],
  ['editorial-end-card', ['native'], 'closing'],
  ['editorial-index', ['native'], 'native-decoration'],
  ['editorial-rule', ['native'], 'native-decoration'],
  ['equipment-nameplate', ['native'], 'native-decoration'],
  ['evidence-caption-bar', ['native'], 'caption'],
  ['evidence-frame', ['native'], 'visual'],
  ['evidence-image-frame', ['native'], 'visual'],
  ['evidence-photo-card', ['native'], 'visual'],
  ['factory-id-plate', ['native'], 'native-decoration'],
  ['frontstage-backstage-tag', ['native'], 'native-decoration'],
  ['funnel-chart', ['native', 'overlay'], 'chart'],
  ['generic-dashboard-card', ['native'], 'native-decoration'],
  ['governance-table', ['native'], 'table'],
  ['growth-flywheel', ['native'], 'flow'],
  ['handoff-checkpoint', ['native'], 'native-decoration'],
  ['handoff-stamp', ['native'], 'native-decoration'],
  ['heatmap-chart', ['native', 'overlay'], 'chart'],
  ['hero-image', ['native', 'overlay'], 'visual'],
  ['hub-spoke-dispatch-map', ['native'], 'flow'],
  ['information-gap', ['native', 'overlay'], 'chart'],
  ['inspection-matrix', ['native'], 'native-decoration'],
  ['kpi-primary-metric', ['native'], 'metric'],
  ['kpi-strip', ['native', 'overlay'], 'metric'],
  ['lacquer-end-card', ['native'], 'closing'],
  ['large-product-frame', ['native'], 'visual'],
  ['launch-rhythm-strip', ['native'], 'flow'],
  ['line-chart', ['native', 'overlay'], 'chart'],
  ['load-curve-band', ['native'], 'native-decoration'],
  ['lookbook-frame', ['native'], 'visual'],
  ['luxury-caption-bar', ['native', 'overlay'], 'caption'],
  ['matrix-chart', ['native', 'overlay'], 'chart'],
  ['member-ladder', ['native'], 'metric'],
  ['metric-highlight', ['native'], 'metric'],
  ['metric-strip', ['native', 'overlay'], 'metric'],
  ['navigation-sequence', ['native'], 'flow'],
  ['page-number', ['native'], 'chrome'],
  ['pareto-chart', ['native', 'overlay'], 'chart'],
  ['patient-journey-band', ['native'], 'flow'],
  ['permission-audit-tag', ['native'], 'native-decoration'],
  ['platform-stage-anchor', ['native'], 'native-decoration'],
  ['portfolio-row-band', ['native'], 'native-decoration'],
  ['priority-line', ['native'], 'native-decoration'],
  ['process-index-rail', ['native'], 'flow'],
  ['process-rail', ['native', 'overlay'], 'flow'],
  ['product-lineage-map', ['native'], 'flow'],
  ['product-matrix', ['native', 'overlay'], 'product'],
  ['product-proof-callout', ['native'], 'product'],
  ['product-story-caption', ['native', 'overlay'], 'caption'],
  ['product-texture-frame', ['native'], 'visual'],
  ['proof-gallery', ['native', 'overlay'], 'visual'],
  ['proof-gallery-grid', ['native', 'overlay'], 'visual'],
  ['prototype-frame', ['native'], 'visual'],
  ['quality-risk-tag', ['native'], 'native-decoration'],
  ['quality-scorecard', ['native'], 'metric'],
  ['responsibility-loop', ['native'], 'flow'],
  ['revenue-expansion-strip', ['native'], 'metric'],
  ['risk-matrix', ['native', 'overlay'], 'governance'],
  ['risk-register', ['native', 'overlay'], 'governance'],
  ['scenario-band', ['native'], 'native-decoration'],
  ['scorecard', ['native', 'overlay'], 'chart'],
  ['section-kicker', ['native'], 'chrome'],
  ['sensitivity-cell', ['native'], 'native-decoration'],
  ['service-blueprint-lane', ['native'], 'flow'],
  ['service-lane-fill', ['native'], 'native-decoration'],
  ['service-touchpoint-card', ['native'], 'visual'],
  ['site-evidence-frame', ['native'], 'visual'],
  ['site-photo-backdrop', ['native'], 'visual'],
  ['sla-chip', ['native'], 'native-decoration'],
  ['source-note', ['native', 'overlay'], 'source'],
  ['source-rights-note', ['native'], 'source'],
  ['space-experience-frame', ['native'], 'visual'],
  ['system-rail', ['native', 'overlay'], 'flow'],
  ['table-with-commentary', ['native', 'overlay'], 'table'],
  ['technical-ruler', ['native'], 'native-decoration'],
  ['telemetry-node', ['native'], 'native-decoration'],
  ['value-chain', ['native', 'overlay'], 'flow'],
  ['value-chain-connector', ['native', 'overlay'], 'flow'],
  ['waterfall-chart', ['native', 'overlay'], 'chart'],
  ['watermark-circle', ['native'], 'native-decoration'],
  ['workflow-caption', ['native'], 'caption'],
  ['workflow-rail', ['native'], 'flow']
];

const COMPONENT_ALIASES = {
  'brand-proof-caption': 'caption-bar',
  'business-proof-rail': 'value-chain',
  'gallery-grid': 'proof-gallery',
  'hero-kpi': 'kpi-strip',
  'hero-kpi-strip': 'kpi-strip',
  'hero-kpis': 'kpi-strip',
  'image-gallery': 'proof-gallery',
  'large-product-frame': 'hero-image',
  'luxury-caption-bar': 'caption-bar',
  'member-ladder': 'kpi-strip',
  'metric-strip': 'kpi-strip',
  'product-grid': 'product-matrix',
  'product-proof-callout': 'product-matrix',
  'product-story-caption': 'caption-bar',
  'source-caption': 'caption-bar',
  'value-chain-connector': 'value-chain'
};

const COMPONENT_DATA_REQUIREMENTS = {
  'bar-chart': ['chartSpec|metrics|rows|series'],
  'beauty-channel-structure': ['chartSpec|channelStructure|channelEfficiency'],
  'beauty-efficacy-table': ['chartSpec|rows|products'],
  'beauty-member-repurchase': ['chartSpec|metrics|memberCohorts'],
  'beauty-price-band-matrix': ['chartSpec|products|priceBands'],
  'beauty-proof-gallery': ['images|visual.images|cards'],
  'beauty-review-sentiment': ['chartSpec|reviews|sentiment'],
  'beauty-sku-matrix': ['chartSpec|products|productStory'],
  'beauty-social-funnel': ['chartSpec|funnel|socialFunnel'],
  'beauty-sustainability-matrix': ['chartSpec|rows|sustainability'],
  'caption-bar': ['caption|subtitle|claim|proof.explanation'],
  'chart-commentary-panel': ['claim|subtitle|note|businessLogic'],
  'commentary-panel': ['claim|note|businessLogic|decision'],
  'content-card-grid': ['cards|items|modules|values|sections'],
  'funnel-chart': ['chartSpec|funnel|steps'],
  'governance-table': ['rows|risks|controls|responsibilities'],
  'heatmap-chart': ['chartSpec|matrix|rows'],
  'hero-image': ['image|images|visual.image|visual.images|visual.mode|product'],
  'information-gap': ['chartSpec.informationGap|informationGap'],
  'kpi-primary-metric': ['metrics'],
  'kpi-strip': ['metrics'],
  'line-chart': ['chartSpec|monthlyPulse|monthlyTrend|trend'],
  'matrix-chart': ['chartSpec|matrix|rows'],
  'navigation-sequence': ['items|sections'],
  'pareto-chart': ['chartSpec|pareto|rows'],
  'process-rail': ['phases|actions|steps|timeline|milestones'],
  'product-matrix': ['products|productStory|product|cards'],
  'proof-gallery': ['images|visual.images|cards|image|visual.image'],
  'proof-gallery-grid': ['images|visual.images|cards|image|visual.image'],
  'risk-matrix': ['matrix|rows|risks|controls'],
  'risk-register': ['rows|risks|controls|riskRegister|riskMatrix'],
  'scorecard': ['chartSpec|metrics'],
  'source-note': ['sourceNote|source_note|proof.sourceNote'],
  'system-rail': ['layers|architecture|systemMap|topology|capabilityMap|platformCapabilities|valueChain|capitals'],
  'table-with-commentary': ['rows|headers|table'],
  'value-chain': ['drivers|actions|outcomes|valueChain|layers|capitals'],
  'waterfall-chart': ['chartSpec|bridge|waterfallBridge|targetBridge']
};

const COMPONENT_CAPABILITIES = Object.fromEntries(CAPABILITY_IDS.map(([id, supportedModes, family]) => [id, {
  id,
  aliases: Object.entries(COMPONENT_ALIASES).filter(([, target]) => target === id).map(([alias]) => alias),
  supportedModes,
  family,
  ownershipPolicy: supportedModes.includes('overlay') ? 'native-or-overlay' : 'native-only',
  dataRequirements: COMPONENT_DATA_REQUIREMENTS[id] || []
}]));

function componentCapabilityFor(id = '') {
  const key = String(id || '');
  return COMPONENT_CAPABILITIES[key] || COMPONENT_CAPABILITIES[COMPONENT_ALIASES[key]] || null;
}

function hasComponentCapability(id = '') {
  return Boolean(componentCapabilityFor(id));
}

module.exports = {
  COMPONENT_ALIASES,
  COMPONENT_CAPABILITIES,
  COMPONENT_DATA_REQUIREMENTS,
  componentCapabilityFor,
  hasComponentCapability,
  renderBarChart,
  renderBeautyChannelStructure,
  renderBeautyEfficacyTable,
  renderBeautyMemberRepurchase,
  renderBeautyPriceBandMatrix,
  renderBeautyProofGallery,
  renderBeautyReviewSentiment,
  renderBeautySkuMatrix,
  renderBeautySocialFunnel,
  renderBeautySustainabilityMatrix,
  renderChartSpec,
  renderFunnelChart,
  renderHeatmapChart,
  renderKpiStrip,
  renderLineChart,
  renderMatrixChart,
  renderParetoChart,
  renderProofGallery,
  renderRiskRegister,
  renderScorecard,
  renderTableWithCommentary,
  renderWaterfallChart,
  renderValueChain
};
