const RENDERER_CONTEXT_CONTRACT = {
  colors: ['colors', 'presentationSpec', 'panelFill', 'surfaceFill'],
  text: ['addText', 'addLabel', 'addNumber', 'sectionKicker', 'footerText', 'publicSlideNote', 'copyFallback', 'copyPolicyList', 'typeSize', 'profileFont', 'itemTitle', 'itemBody', 'itemBodyNoEllipsis'],
  shapes: ['addRect', 'addHairline', 'addArrowLine', 'addArrowBetweenRects', 'addClockwiseLoopConnectors', 'PageNumber', 'lightCanvas', 'stageCanvas', 'addPhotoPanel', 'addSmartPhotoPanel', 'addDarkBreathingCircle', 'addLightBreathingCircle', 'addPulseCurve'],
  components: ['componentRendererContext', 'renderChartSpec', 'recordChartConsumption'],
  assets: ['fileExists', 'designForSlide', 'galleryImages', 'mediaForRole', 'resolveAssetPath', 'smartPhotoFit'],
  variants: ['variantOf'],
  business: [
    'PageNumber',
    'addVisualPhotoPanel',
    'canvasHeight',
    'canvasWidth',
    'copyFallback',
    'footerText',
    'itemBody',
    'itemTitle',
    'panelFill',
    'profileFont',
    'publicSlideNote',
    'reportBoardNeedsRightOverlayRail',
    'sectionKicker'
  ],
  chapter: [
    'PageNumber',
    'addArrowLine',
    'addDarkBreathingCircle',
    'addHairline',
    'addLabel',
    'addNumber',
    'addPhotoPanel',
    'addRect',
    'addText',
    'canvasWidth',
    'footerText',
    'galleryImages',
    'itemBody',
    'itemTitle',
    'lightCanvas',
    'panelFill',
    'profileFont',
    'publicSlideNote',
    'sectionKicker',
    'stageCanvas',
    'variantOf'
  ],
  general: [
    'addHairline',
    'addLabel',
    'addRect',
    'addText',
    'addVisualPhotoPanel',
    'masterLight',
    'profileFont'
  ],
  toc: [
    'PageNumber',
    'addHairline',
    'addRect',
    'addText',
    'canvasHeight',
    'canvasWidth',
    'copyFallback',
    'copyPolicyList',
    'footerText',
    'glassPanel',
    'isCompanyIntroPlan'
  ],
  manifesto: [
    'addDarkBreathingCircle',
    'addHairline',
    'addLabel',
    'addNumber',
    'addRect',
    'addText',
    'footerText',
    'itemBody',
    'itemTitle',
    'lightCanvas',
    'panelFill',
    'sectionKicker',
    'stageCanvas',
    'variantOf'
  ],
  profile: [
    'EvidenceImageFrame',
    'MetricStrip',
    'addDarkBreathingCircle',
    'addEquipmentNameplate',
    'addHairline',
    'addLabel',
    'addNumber',
    'addPhotoPanel',
    'addRect',
    'addText',
    'designForSlide',
    'fileExists',
    'footerText',
    'galleryImages',
    'imageAspect',
    'isCompanyIntroPlan',
    'lightCanvas',
    'mediaForRole',
    'panelFill',
    'publicSlideNote',
    'resolveAssetPath',
    'sectionKicker',
    'stageCanvas'
  ],
  financial: [
    'PageNumber',
    'addArrowLine',
    'addHairline',
    'addLabel',
    'addNumber',
    'addRect',
    'addText',
    'brandWorldBusinessProof',
    'chartSpecToComponentId',
    'compactEvidenceCaption',
    'componentRendererContext',
    'consumerProofPhotoGrid',
    'footerText',
    'formatMetricDelta',
    'isVisualIndustry',
    'itemBody',
    'itemTitle',
    'lightCanvas',
    'panelFill',
    'productEvidenceStory',
    'publicSlideNote',
    'recordChartConsumption',
    'renderChartSpec',
    'routeChartSpec',
    'sectionKicker',
    'variantOf',
    'sustainabilityProofSpread'
  ],
  beauty: [
    'PageNumber',
    'addHairline',
    'addLabel',
    'addNumber',
    'addRect',
    'addSmartPhotoPanel',
    'addText',
    'chooseFourImageLayout',
    'designForSlide',
    'fileExists',
    'footerText',
    'genericShowcaseField',
    'imagePathFromItem',
    'itemBody',
    'itemTitle',
    'lightCanvas',
    'panelFill',
    'sectionKicker',
    'variantOf'
  ],
  closing: [
    'ContactBlock',
    'activePlan',
    'addArrowLine',
    'addDarkBreathingCircle',
    'addEnergyLens',
    'addEnergyMotionBackdrop',
    'addEnergyPhotoBackdrop',
    'addHairline',
    'addLabel',
    'addLightBreathingCircle',
    'addNumber',
    'addPhotoPanel',
    'addRect',
    'addText',
    'addVisualPhotoBackdrop',
    'canvasHeight',
    'canvasWidth',
    'colors',
    'copyFallback',
    'copyPolicyList',
    'coverMetaText',
    'designForSlide',
    'fileExists',
    'footerText',
    'galleryImages',
    'isCompanyIntroPlan',
    'itemBody',
    'itemTitle',
    'lightCanvas',
    'mediaForRole',
    'metaDisabled',
    'panelFill',
    'presentationSpec',
    'profileFont',
    'resolveAssetPath',
    'sectionKicker',
    'smartPhotoFit',
    'stageCanvas',
    'surfaceFill',
    'typeSize',
    'variantOf'
  ],
  cover: [
    'addArrowLine',
    'addDarkBreathingCircle',
    'addDeckMeta',
    'addEnergyLens',
    'addEnergyMotionBackdrop',
    'addEnergyPhotoBackdrop',
    'addHairline',
    'addLabel',
    'addLightBreathingCircle',
    'addNumber',
    'addPhotoPanel',
    'addPulseCurve',
    'addRect',
    'addText',
    'addVisualPhotoBackdrop',
    'canvasHeight',
    'canvasWidth',
    'colors',
    'copyFallback',
    'designForSlide',
    'fileExists',
    'footerText',
    'genericShowcaseField',
    'industryProfile',
    'isCompanyIntroPlan',
    'itemBody',
    'itemTitle',
    'lightCanvas',
    'masterDark',
    'metaDisabled',
    'panelFill',
    'presentationSpec',
    'profile',
    'profileFont',
    'stageCanvas',
    'surfaceFill',
    'typeToken',
    'typeSize',
    'variantOf'
  ],
  timeline: [
    'addClockwiseLoopConnectors',
    'compactEvidenceCaption'
  ],
  risk: [
    'PageNumber',
    'addClockwiseLoopConnectors',
    'addDarkBreathingCircle',
    'addHairline',
    'addLabel',
    'addNumber',
    'addRect',
    'addText',
    'colors',
    'compactEvidenceCaption',
    'footerText',
    'itemBody',
    'itemTitle',
    'lightCanvas',
    'panelFill',
    'sectionKicker',
    'stageCanvas',
    'variantOf'
  ],
  strategy: [
    'addArrowLine',
    'addHairline',
    'addLabel',
    'addNumber',
    'addRect',
    'addText',
    'brandWorldBusinessProof',
    'canvasHeight',
    'canvasWidth',
    'footerText',
    'glassPanel',
    'industryProfile',
    'lightCanvas',
    'panelFill',
    'sectionKicker',
    'singleObjectConceptMapSlide',
    'valueCreationProcessMapSlide',
    'variantOf'
  ],
  evidenceGallery: [
    'PageNumber',
    'addArrowBetweenRects',
    'addArrowLine',
    'addDarkBreathingCircle',
    'addEvidenceCaptionStack',
    'addHairline',
    'addLabel',
    'addLightBreathingCircle',
    'addNumber',
    'addPhotoPanel',
    'addPulseCurve',
    'addRect',
    'addSmartPhotoPanel',
    'addText',
    'brandWorldBusinessProof',
    'chooseEvidenceImageLayout',
    'colors',
    'compactEvidenceCaption',
    'fileExists',
    'footerText',
    'galleryImages',
    'genericShowcaseField',
    'itemBody',
    'itemBodyNoEllipsis',
    'itemTitle',
    'lightCanvas',
    'panelFill',
    'resolveAssetPath',
    'sectionKicker',
    'stageCanvas',
    'variantOf'
  ],
  financialScorecard: [
    'addArrowLine',
    'addHairline',
    'addLabel',
    'addNumber',
    'addRect',
    'addText',
    'colors',
    'footerText',
    'formatMetricDelta',
    'lightCanvas',
    'panelFill',
    'sectionKicker'
  ]
};

const RENDERER_COLOR_CONTRACT = {
  closing: ['accent', 'body', 'captionOnImage', 'cyan', 'ink', 'ink2', 'line', 'muted', 'softBlue', 'text', 'violet', 'white'],
  cover: ['accent', 'body', 'captionOnImage', 'cyan', 'ink', 'ink2', 'line', 'muted', 'panelAlt', 'softBlue', 'text', 'violet', 'white'],
  evidenceGallery: ['accent', 'body', 'captionOnImage', 'cyan', 'ink', 'ink2', 'line', 'muted', 'panelAlt', 'softBlue', 'text', 'violet', 'white'],
  financialScorecard: ['accent', 'body', 'captionOnImage', 'cyan', 'ink', 'line', 'muted', 'risk', 'softBlue', 'text', 'violet', 'white'],
  risk: ['accent', 'body', 'captionOnImage', 'cyan', 'ink', 'ink2', 'line', 'muted', 'risk', 'text', 'violet', 'white']
};

function createRendererContext(api = {}) {
  return Object.freeze(Object.assign({}, api, {
    colors() {
      return typeof api.colors === 'function' ? api.colors() : (api.colors || {});
    }
  }));
}

function missingRendererContextKeys(ctx = {}, groups = Object.keys(RENDERER_CONTEXT_CONTRACT)) {
  return groups.flatMap(group => (RENDERER_CONTEXT_CONTRACT[group] || []).filter(key => ctx[key] == null));
}

function missingRendererColorTokens(ctx = {}, groups = Object.keys(RENDERER_COLOR_CONTRACT)) {
  const colors = typeof ctx.colors === 'function' ? ctx.colors() : (ctx.colors || {});
  return groups.flatMap(group => (RENDERER_COLOR_CONTRACT[group] || [])
    .filter(token => colors[token] == null)
    .map(token => `${group}.${token}`));
}

function assertRendererContext(ctx = {}, groups = [], opts = {}) {
  const label = opts.label || 'renderer context';
  const missingKeys = missingRendererContextKeys(ctx, groups);
  const missingColors = opts.colors === false ? [] : missingRendererColorTokens(ctx, groups);
  if (missingKeys.length || missingColors.length) {
    const parts = [];
    if (missingKeys.length) parts.push(`missing helpers: ${missingKeys.join(', ')}`);
    if (missingColors.length) parts.push(`missing colors: ${missingColors.join(', ')}`);
    throw new Error(`${label} contract failed (${groups.join(', ')}): ${parts.join('; ')}`);
  }
  return ctx;
}

module.exports = {
  RENDERER_CONTEXT_CONTRACT,
  RENDERER_COLOR_CONTRACT,
  assertRendererContext,
  createRendererContext,
  missingRendererColorTokens,
  missingRendererContextKeys
};
