#!/usr/bin/env node
/* Validate a PPTX generated by premium-commercial-ppt. */
const fs = require('fs');
const path = require('path');
const cp = require('child_process');

function usage() {
  console.error('Usage: node scripts/validate_pptx.js <file.pptx> [--expect-slides N] [--require term1,term2] [--preview-dir dir] [--allow-placeholders]');
  process.exit(2);
}
const args = process.argv.slice(2);
if (!args[0]) usage();
const file = path.resolve(args[0]);
let expectSlides = null;
let requireTerms = [];
let previewDir = null;
let allowPlaceholders = false;
for (let i=1; i<args.length; i++) {
  if (args[i] === '--expect-slides') expectSlides = Number(args[++i]);
  else if (args[i] === '--require') requireTerms = String(args[++i] || '').split(',').filter(Boolean);
  else if (args[i] === '--preview-dir') previewDir = path.resolve(String(args[++i] || ''));
  else if (args[i] === '--allow-placeholders') allowPlaceholders = true;
  else usage();
}
function run(cmd, argv, opts={}) {
  return cp.execFileSync(cmd, argv, Object.assign({ encoding:'utf8' }, opts));
}
function fail(msg, extra={}) {
  console.error(JSON.stringify({ success:false, error:msg, ...extra }, null, 2));
  process.exit(1);
}
if (!fs.existsSync(file)) fail('file_not_found', { file });
if (path.extname(file).toLowerCase() !== '.pptx') fail('not_pptx_extension', { file });
let zipList;
try {
  run('unzip', ['-t', file], { stdio:['ignore','pipe','pipe'] });
  zipList = run('unzip', ['-Z1', file]);
} catch (e) {
  fail('zip_structure_invalid_or_unzip_missing', { file, detail:String(e.message || e) });
}
const entries = zipList.split(/\r?\n/).filter(Boolean);
const slides = entries.filter(x => /^ppt\/slides\/slide\d+\.xml$/.test(x)).sort((a,b)=>Number(a.match(/slide(\d+)/)[1])-Number(b.match(/slide(\d+)/)[1]));
if (!slides.length) fail('no_slides_found', { file });
if (expectSlides != null && slides.length !== expectSlides) fail('slide_count_mismatch', { expected:expectSlides, actual:slides.length });
const textParts = [];
for (const s of slides) {
  let xml = '';
  try { xml = run('unzip', ['-p', file, s]); } catch (_) {}
  const matches = [...xml.matchAll(/<a:t>(.*?)<\/a:t>/g)].map(m => m[1]
    .replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&apos;/g,"'"));
  textParts.push(...matches);
}
const allText = textParts.join('\n');
if (!/[\u4e00-\u9fff]/.test(allText)) fail('no_chinese_text_extracted', { file, slides:slides.length });
const badPlaceholders = ['lorem', 'ipsum', 'xxxx', 'TODO', '示例', '测试稿', '验收稿', '占位', '待补充', '请批评指正'];
const foundBad = allowPlaceholders ? [] : badPlaceholders.filter(p => allText.toLowerCase().includes(p.toLowerCase()));
if (foundBad.length) fail('visible_scaffold_text_found', { foundBad });
const missing = requireTerms.filter(t => !allText.includes(t));
if (missing.length) fail('required_terms_missing', { missing });
function applePath(p) {
  return String(p).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}
function exportPreviews() {
  if (!previewDir) return [];
  fs.mkdirSync(previewDir, { recursive:true });
  const keynoteApp = '/Applications/Keynote.app';
  if (!fs.existsSync(keynoteApp)) fail('preview_export_requires_keynote', { previewDir });
  try {
    run('osascript', [
      '-e', 'tell application "Keynote"',
      '-e', `set theDoc to open POSIX file "${applePath(file)}"`,
      '-e', `export theDoc to POSIX file "${applePath(previewDir)}" as slide images with properties {image format:PNG}`,
      '-e', 'close theDoc saving no',
      '-e', 'end tell'
    ], { timeout:90000 });
  } catch (e) {
    fail('preview_export_failed', { previewDir, detail:String(e.message || e) });
  }
  return fs.readdirSync(previewDir)
    .filter(x => /\.png$/i.test(x))
    .sort()
    .map(x => path.join(previewDir, x));
}
const previewFiles = exportPreviews();
const result = {
  success: true,
  file,
  size_bytes: fs.statSync(file).size,
  slide_count: slides.length,
  preview_dir: previewDir,
  preview_count: previewFiles.length,
  preview_files: previewFiles.slice(0, 20),
  text_sample: textParts.slice(0, 30),
  checks: {
    exists: true,
    pptx_extension: true,
    zip_ok: true,
    chinese_text: true,
    no_visible_scaffold_text: true,
    required_terms_present: missing.length === 0
  }
};
console.log(JSON.stringify(result, null, 2));
